Objective:

Students will be able to implement Bidirectional Associative Memory Network algorithm for
the given dataset.

Students will be able to compute the Weight Matrix using the BAM Algorithm and Test the
BAM model for the input patterns.

Theory:

The architecture of BAM network consists of two layers of neurons which are connected by directed
weighted pare interconnections. The network dynamics involve two layers of interaction. The BAM
network iterates by sending the signals back and forth between the two layers until all the neurons
reach equilibrium. The weights associated with the network are bidirectional. Thus, BAM can respond
to the inputs in either layer.

In [13]:
import numpy as np

# Set A: Input Pattern
x1 = np.array([1, 1, 1, 1, 1, 1]).reshape(6, 1)
x2 = np.array([-1, -1, -1, -1, -1, -1]).reshape(6, 1)
x3 = np.array([1, 1, -1, -1, 1, 1]).reshape(6, 1)
x4 = np.array([-1, -1, 1, 1, -1, -1]).reshape(6, 1)
# Set B: Target Pattern
y1 = np.array([1, 1, 1]).reshape(3, 1)
y2 = np.array([-1, -1, -1]).reshape(3, 1)
y3 = np.array([1, -1, 1]).reshape(3, 1)
y4 = np.array([-1, 1, -1]).reshape(3, 1)

print("Set A: Input Pattern, Set B: Target Pattern")
print("\nThe input for pattern 1 is")
print(x1)
print("\nThe target for pattern 1 is")
print(y1)
print("\nThe input for pattern 2 is")
print(x2)
print("\nThe target for pattern 2 is")
print(y2)
print("\nThe input for pattern 3 is")
print(x3)
print("\nThe target for pattern 3 is")
print(y3)
print("\nThe input for pattern 4 is")
print(x4)
print("\nThe target for pattern 4 is")
print(y4)
print("\n------------------------------")



Set A: Input Pattern, Set B: Target Pattern

The input for pattern 1 is
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]]

The target for pattern 1 is
[[1]
 [1]
 [1]]

The input for pattern 2 is
[[-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]]

The target for pattern 2 is
[[-1]
 [-1]
 [-1]]

The input for pattern 3 is
[[ 1]
 [ 1]
 [-1]
 [-1]
 [ 1]
 [ 1]]

The target for pattern 3 is
[[ 1]
 [-1]
 [ 1]]

The input for pattern 4 is
[[-1]
 [-1]
 [ 1]
 [ 1]
 [-1]
 [-1]]

The target for pattern 4 is
[[-1]
 [ 1]
 [-1]]

------------------------------


In [4]:
inputSet = np.concatenate((x1, x2, x3, x4), axis = 1)
targetSet = np.concatenate((y1.T, y2.T, y3.T, y4.T), axis = 0)
print("\nWeight matrix:")
weight = np.dot(inputSet, targetSet)
print(weight)
print("\n------------------------------")


Weight matrix:
[[4 0 4]
 [4 0 4]
 [0 4 0]
 [0 4 0]
 [4 0 4]
 [4 0 4]]

------------------------------


In [15]:
print("\nTesting for input patterns: Set A")
def testInputs(x, weight):
    y = np.dot(weight.T, x)
    y[y < 0] = -1
    y[y >= 0] = 1
    return np.array(y)
print("\nOutput of input pattern 1")
print(testInputs(x1, weight))
print("\nOutput of input pattern 2")
print(testInputs(x2, weight))
print("\nOutput of input pattern 3")
print(testInputs(x3, weight))
print("\nOutput of input pattern 4")
print(testInputs(x4, weight))



Testing for input patterns: Set A

Output of input pattern 1
[[1]
 [1]
 [1]]

Output of input pattern 2
[[-1]
 [-1]
 [-1]]

Output of input pattern 3
[[ 1]
 [-1]
 [ 1]]

Output of input pattern 4
[[-1]
 [ 1]
 [-1]]


In [16]:
print("\nTesting for target patterns: Set B")
def testTargets(y, weight):
    x = np.dot(weight, y)
    x[x <= 0] = -1
    x[x > 0] = 1
    return np.array(x)
print("\nOutput of target pattern 1")
print(testTargets(y1, weight))
print("\nOutput of target pattern 2")
print(testTargets(y2, weight))
print("\nOutput of target pattern 3")
print(testTargets(y3, weight))
print("\nOutput of target pattern 4")
print(testTargets(y4, weight))



Testing for target patterns: Set B

Output of target pattern 1
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]]

Output of target pattern 2
[[-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]]

Output of target pattern 3
[[ 1]
 [ 1]
 [-1]
 [-1]
 [ 1]
 [ 1]]

Output of target pattern 4
[[-1]
 [-1]
 [ 1]
 [ 1]
 [-1]
 [-1]]


In [18]:
#Conclusion:
'''Bidirectional Associative Memories (BAM) is system that allow to associate pairs of patterns. Once a
memory has learned, patterns can be recalled in two directions. BAMs have many applications in
pattern recognition and image processing. BAM compute the weight matrix and Test the BAM
model for the input patterns.'''

'Bidirectional Associative Memories (BAM) is system that allow to associate pairs of patterns. Once a\nmemory has learned, patterns can be recalled in two directions. BAMs have many applications in\npattern recognition and image processing. BAM compute the weight matrix and Test the BAM\nmodel for the input patterns.'